In [1]:
%env OMP_NUM_THREADS=1

import numpy as np
from multiprocessing import Pool, cpu_count

env: OMP_NUM_THREADS=1


In [ ]:
# https://numba.readthedocs.io/en/stable/user/parallel.html

In [2]:
def gcd(x, y):
    while (y):
        x, y = y, x % y
    return x

def phi(n):
    cnt = 0
    for i in range(1, n):
        if gcd(i, n) == 1:
            cnt += 1
    return cnt

In [3]:
a = np.random.randint(low=1, high=10**4, size=1000)

In [4]:
%%time

[phi(n) for n in a]

CPU times: user 5.99 s, sys: 4.94 ms, total: 5.99 s
Wall time: 5.99 s


[2208,
 2476,
 4224,
 6540,
 1786,
 3802,
 4284,
 2048,
 2448,
 3744,
 2160,
 3744,
 5808,
 1464,
 1608,
 4912,
 6970,
 3600,
 1272,
 1640,
 1140,
 84,
 9490,
 528,
 6120,
 584,
 3168,
 3212,
 3166,
 2772,
 1780,
 1112,
 4320,
 342,
 1512,
 3720,
 4156,
 144,
 876,
 1626,
 3236,
 6120,
 2160,
 2472,
 5736,
 3200,
 4872,
 1530,
 4440,
 480,
 1236,
 384,
 2096,
 502,
 3120,
 1228,
 1140,
 312,
 22,
 504,
 4680,
 336,
 4224,
 468,
 2880,
 8448,
 2752,
 1512,
 2664,
 1296,
 672,
 8170,
 56,
 1376,
 7792,
 5992,
 2592,
 4320,
 4768,
 3768,
 2304,
 2448,
 880,
 466,
 3528,
 2728,
 3060,
 2952,
 2176,
 3696,
 4012,
 4512,
 3024,
 2520,
 2160,
 1472,
 564,
 220,
 576,
 5060,
 1520,
 3300,
 956,
 660,
 3200,
 1696,
 2040,
 6516,
 4420,
 2916,
 4792,
 4544,
 504,
 2464,
 2640,
 3120,
 5010,
 5184,
 4518,
 6876,
 1344,
 1332,
 7144,
 1864,
 1392,
 3672,
 2332,
 8220,
 4648,
 1560,
 576,
 7560,
 3928,
 3552,
 2382,
 1652,
 1440,
 5928,
 1352,
 2916,
 5760,
 5200,
 6444,
 768,
 1728,
 6816,
 476,
 

In [5]:
%%time

with Pool(processes=cpu_count()) as pool:
    res = pool.map(phi, a)

CPU times: user 89.3 ms, sys: 35.4 ms, total: 125 ms
Wall time: 1.18 s


In [6]:
res

[2208,
 2476,
 4224,
 6540,
 1786,
 3802,
 4284,
 2048,
 2448,
 3744,
 2160,
 3744,
 5808,
 1464,
 1608,
 4912,
 6970,
 3600,
 1272,
 1640,
 1140,
 84,
 9490,
 528,
 6120,
 584,
 3168,
 3212,
 3166,
 2772,
 1780,
 1112,
 4320,
 342,
 1512,
 3720,
 4156,
 144,
 876,
 1626,
 3236,
 6120,
 2160,
 2472,
 5736,
 3200,
 4872,
 1530,
 4440,
 480,
 1236,
 384,
 2096,
 502,
 3120,
 1228,
 1140,
 312,
 22,
 504,
 4680,
 336,
 4224,
 468,
 2880,
 8448,
 2752,
 1512,
 2664,
 1296,
 672,
 8170,
 56,
 1376,
 7792,
 5992,
 2592,
 4320,
 4768,
 3768,
 2304,
 2448,
 880,
 466,
 3528,
 2728,
 3060,
 2952,
 2176,
 3696,
 4012,
 4512,
 3024,
 2520,
 2160,
 1472,
 564,
 220,
 576,
 5060,
 1520,
 3300,
 956,
 660,
 3200,
 1696,
 2040,
 6516,
 4420,
 2916,
 4792,
 4544,
 504,
 2464,
 2640,
 3120,
 5010,
 5184,
 4518,
 6876,
 1344,
 1332,
 7144,
 1864,
 1392,
 3672,
 2332,
 8220,
 4648,
 1560,
 576,
 7560,
 3928,
 3552,
 2382,
 1652,
 1440,
 5928,
 1352,
 2916,
 5760,
 5200,
 6444,
 768,
 1728,
 6816,
 476,
 

In [7]:
np.cos(np.pi)

-1.0

In [8]:
np.cos(np.random.randn(10, 10))

array([[ 0.93291266,  0.02505799,  0.86209626,  0.58781047,  0.96687729,
         0.09958573,  0.76930327,  0.83447763,  0.08458411,  0.94043674],
       [ 0.93277737, -0.271011  ,  0.97521285,  0.58306297,  0.75637478,
         0.36933509,  0.9775746 ,  0.89788106,  0.75770165,  0.73772266],
       [ 0.99490287,  0.93204006,  0.98342752,  0.99359903,  0.51199358,
         0.84018047,  0.98284762,  0.91171783,  0.98457061,  0.84745656],
       [ 0.72661786,  0.27023566,  0.97528635,  0.85439654,  0.91494344,
        -0.12470009,  0.94917005,  0.96192259, -0.15701638,  0.79442349],
       [ 0.94477662,  0.91298236,  0.94487511,  0.46813125,  0.96876225,
         0.66110194,  0.44931016,  0.61405326,  0.88368981,  0.99950342],
       [ 0.99875384, -0.44216818,  0.91706441,  0.9975631 ,  0.94632546,
         0.99838721,  0.70864752,  0.98993189,  0.88887361,  0.8568073 ],
       [ 0.87712009,  0.01793832,  0.71559217, -0.86951046,  0.19548202,
         0.83851509,  0.26074808,  0.84180023

In [10]:
import numba

In [11]:
@numba.jit(nopython=True)
def gcd_numba(x, y):
    while (y):
        x, y = y, x % y
    return x

@numba.vectorize([numba.int64(numba.int64)], nopython=True,
                 target='parallel')
def phi_numba(n):
    cnt = 0
    for i in range(1, n):
        if gcd_numba(i, n) == 1:
            cnt += 1
    return cnt

In [12]:
%%time

res = phi_numba(a)

CPU times: user 404 ms, sys: 7.95 ms, total: 412 ms
Wall time: 77.2 ms


In [13]:
gcd_numba(15, 25)

5

In [18]:
from numba import prange

@numba.jit(nopython=True, parallel=True)
def my_sum(a, b):
    c = np.zeros_like(a)
    for i in prange(a.shape[0]):
        c[i] = (a[i]**2 + b[i]**3)**5
    return c

In [16]:
a = np.random.randn(10**8)
b = np.random.randn(10**8)

In [21]:
%%time

c = my_sum(a, b)

CPU times: user 1.07 s, sys: 335 ms, total: 1.41 s
Wall time: 542 ms


In [22]:
%%time

c = (a**2 + b**3)**5

CPU times: user 5.58 s, sys: 388 ms, total: 5.96 s
Wall time: 5.97 s


In [55]:
@numba.jit(nopython=True, parallel=True)
def my_sum2(a):
    s = -np.inf
    for i in prange(a.shape[0]):
        s = max(s, a[i])
    return s

In [52]:
a = np.random.randn(10**4)

In [53]:
%%time

my_sum2(a)

CPU times: user 364 ms, sys: 0 ns, total: 364 ms
Wall time: 363 ms


4.05250267048772

In [54]:
a.max()

4.05250267048772

In [56]:
@numba.jit(nopython=True, parallel=True)
def my_sum3(a):
    s = np.zeros(a.shape[1:])
    for i in prange(a.shape[0]):
        s += a[i]
    return s

In [57]:
a = np.random.randn(10**4, 10**4)

In [58]:
%%time

my_sum3(a)

CPU times: user 961 ms, sys: 4.52 ms, total: 966 ms
Wall time: 847 ms


array([  29.15760166, -180.90488   ,   91.37390668, ...,   16.65671234,
        -87.04931134,  -22.84465473])

In [59]:
a.sum(0)

array([  29.15760166, -180.90488   ,   91.37390668, ...,   16.65671234,
        -87.04931134,  -22.84465473])

In [60]:
@numba.jit(nopython=True, parallel=True)
def my_sum4(a):
    s = np.zeros(a.shape[1:])
    for i in prange(a.shape[0]):
        s[:] += a[i]
    return s

In [66]:
%%time

my_sum4(a)

CPU times: user 398 ms, sys: 24 µs, total: 398 ms
Wall time: 95 ms


array([  17.2617336 , -200.88276583,  105.83855337, ...,   19.51732113,
        -72.22883484,  -14.80179551])

In [67]:
@numba.jit(nopython=True, parallel=True)
def my_sum5(a):
    s = np.zeros(a.shape[1:])
    for i in prange(a.shape[0]):
        s[:1] += a[i, 0]
    return s

In [76]:
%%time

my_sum5(a)

CPU times: user 3.79 ms, sys: 275 µs, total: 4.07 ms
Wall time: 1.42 ms


array([106.35372161,   0.        ,   0.        , ...,   0.        ,
         0.        ,   0.        ])

In [79]:
@numba.jit(nopython=True, parallel=True)
def my_sum6(a):
    s = np.zeros(a.shape[1:])
    t = s[:1]
    for i in prange(a.shape[0]):
        t += a[i, 0]
    return s

In [85]:
%%time

my_sum6(a)

CPU times: user 0 ns, sys: 3.13 ms, total: 3.13 ms
Wall time: 967 µs


array([29.15760166,  0.        ,  0.        , ...,  0.        ,
        0.        ,  0.        ])

In [114]:
@numba.jit(nopython=True, parallel=True)
def my_sum7(a):
    s = 5
    for i in prange(a.shape[0]):
        s = s + a[i]
    s -= 5
    return s

In [115]:
a = np.random.randn(10**8)

In [116]:
%%time

my_sum7(a)

CPU times: user 502 ms, sys: 11.6 ms, total: 514 ms
Wall time: 361 ms


-15293.423426661895

In [117]:
a.sum()

-15323.423426661484

In [119]:
@numba.jit(nopython=True, parallel=True)
def my_func(x):
    n = x.shape[0]
    
    a = np.zeros_like(x)
    b = np.zeros_like(x)
    s = 0
    
    for i in prange(n):
        a[i] = np.sin(x[i])
    for i in prange(n):
        b[i] = np.cos(a[i]**2)
    for i in prange(n):
        s += b[i]
        
    return s

In [123]:
%%time

my_func(a)

CPU times: user 3.69 s, sys: 713 ms, total: 4.4 s
Wall time: 1.58 s


85500378.66385427

In [127]:
my_sum4.parallel_diagnostics(level=4)

 
 Parallel Accelerator Optimizing:  Function my_sum4, 
/tmp/ipykernel_7852/3513204274.py (1)  


Parallel loop listing for  Function my_sum4, /tmp/ipykernel_7852/3513204274.py (1) 
--------------------------------------------|loop #ID
@numba.jit(nopython=True, parallel=True)    | 
def my_sum4(a):                             | 
    s = np.zeros(a.shape[1:])---------------| #10
    for i in prange(a.shape[0]):------------| #11
        s[:] += a[i]------------------------| #9
    return s                                | 
--------------------------------- Fusing loops ---------------------------------
Attempting fusion of parallel loops (combines loops with similar properties)...
  Trying to fuse loops #10 and #11:
    - fusion failed: loop dimension mismatched in axis 0. slice(0, a_size1.545, 
1) != slice(0, $30binary_subscr.14, 1)
----------------------------- Before Optimisation ------------------------------
Parallel region 0:
+--11 (parallel)
   +--9 (parallel)


-------------------

In [124]:
my_func.parallel_diagnostics(level=4)

 
 Parallel Accelerator Optimizing:  Function my_func, 
/tmp/ipykernel_7852/2190622174.py (1)  


Parallel loop listing for  Function my_func, /tmp/ipykernel_7852/2190622174.py (1) 
--------------------------------------------|loop #ID
@numba.jit(nopython=True, parallel=True)    | 
def my_func(x):                             | 
    n = x.shape[0]                          | 
                                            | 
    a = np.zeros_like(x)                    | 
    b = np.zeros_like(x)                    | 
    s = 0                                   | 
                                            | 
    for i in prange(n):---------------------| #28
        a[i] = np.sin(x[i])                 | 
    for i in prange(n):---------------------| #26
        b[i] = np.cos(a[i]**2)              | 
    for i in prange(n):---------------------| #27
        s += b[i]                           | 
                                            | 
    return s                                | 
---

In [128]:
@numba.jit(nopython=True, parallel=True)
def invalid():
    z = []
    for i in prange(10000):
        z.append(i)
    return z

In [129]:
invalid()

AssertionError: Failed in nopython mode pipeline (step: native lowering)
Failed in nopython mode pipeline (step: native lowering)


In [140]:
from numba import get_num_threads, get_thread_id

In [161]:
@numba.jit(nopython=True, parallel=True)
def invalid():
    n = get_num_threads()
    z = [0 for _ in range(n)]
    for i in prange(10**4):
        z[get_thread_id()] += i
    return z

In [162]:
n = 6
z = [0 for _ in range(n)]
for i in prange(10):
    z[i % n] += i

In [163]:
z

[6, 8, 10, 12, 4, 5]

In [164]:
invalid()

[34723611, 15271389, 0, 0, 0, 0]

In [166]:
@numba.jit(nopython=True, parallel=True)
def func1():
    n = 100
    vals = np.empty(n)
    for i in prange(n):
        cur = i + 1
        for j in range(i):
            if cur % 2 == 0:
                cur //= 2
            else:
                cur = cur * 3 + 1
        vals[i] = cur
    return vals

In [168]:
%%timeit

res = func1()

93.3 µs ± 6.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [171]:
from numba import parallel_chunksize, set_parallel_chunksize, \
                  get_parallel_chunksize

In [172]:
%%timeit

with parallel_chunksize(1):
    res = func1()

55.7 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [174]:
@numba.jit(nopython=True, parallel=True)
def func1(n):
    acc = 0
    print(get_parallel_chunksize()) # Will print 4.
    for i in prange(n):
        print(get_parallel_chunksize()) # Will print 0.
        acc += i
    print(get_parallel_chunksize()) # Will print 4.
    return acc


@numba.jit(nopython=True, parallel=True)
def func2(n):
    acc = 0
    # This version gets the previous chunksize explicitly.
    old_chunksize = get_parallel_chunksize()
    set_parallel_chunksize(8)
    for i in prange(n):
        acc += i
    set_parallel_chunksize(old_chunksize)
    return acc

# This version saves the previous chunksize as returned
# by set_parallel_chunksize.
old_chunksize = set_parallel_chunksize(4)
result1 = func1(12)
result2 = func2(12)
result3 = func1(12)
set_parallel_chunksize(old_chunksize)

4
0
0
0
0
0
0
0
0
0
0
0
0
4
4
0
0
0
0
0
0
0
0
0
0
0
0
4


4

In [175]:
import numpy as np
import numba

@numba.jit(nopython=True)
def power_method(A, v):
    u = v.copy()
    for i in range(3 * 10**3):
        u = A @ u
        u /= np.linalg.norm(u)
    return u

@numba.jit(nopython=True, parallel=True)
def iterate_grid_seq(A, scale, sz):
    assert A.shape[0] == A.shape[1] == 3
    n = A.shape[0]

    results = np.empty((sz**3, n))
    tmp = np.linspace(-scale, scale, sz)
    
    for i1 in range(sz):
        v = np.empty(n, dtype=np.float64)
        v1 = tmp[i1]
        for i2, v2 in enumerate(tmp):
            for i3, v3 in enumerate(tmp):
                v[0] = v1
                v[1] = v2
                v[2] = v3

                u = power_method(A, v)

                idx = i1 * sz**2 + i2 * sz + i3
                results[idx] = u.copy()
    
    return results

@numba.jit(nopython=True, parallel=True)
def iterate_grid_par(A, scale, sz):
    assert A.shape[0] == A.shape[1] == 3
    n = A.shape[0]

    results = np.empty((sz**3, n))
    tmp = np.linspace(-scale, scale, sz)
    
    for i1 in numba.prange(sz):
        v = np.empty(n, dtype=np.float64)
        v1 = tmp[i1]
        for i2, v2 in enumerate(tmp):
            for i3, v3 in enumerate(tmp):
                v[0] = v1
                v[1] = v2
                v[2] = v3

                u = power_method(A, v)

                idx = i1 * sz**2 + i2 * sz + i3
                results[idx] = u.copy()
    
    return results

n = 3
np.random.seed(0)
A = np.random.randn(n, n)

res_seq = iterate_grid_seq(A, 5.0, 20)
res_par = iterate_grid_par(A, 5.0, 20)

print(res_seq.sum())
print(res_par.sum())
print(np.abs(res_seq - res_par).sum())

0.0
0.0
0.0


In [176]:
iterate_grid_par.parallel_diagnostics(level=4)

 
 Parallel Accelerator Optimizing:  Function iterate_grid_par, 
/tmp/ipykernel_7852/1678169338.py (36)  


Parallel loop listing for  Function iterate_grid_par, /tmp/ipykernel_7852/1678169338.py (36) 
---------------------------------------------------|loop #ID
@numba.jit(nopython=True, parallel=True)           | 
def iterate_grid_par(A, scale, sz):                | 
    assert A.shape[0] == A.shape[1] == 3           | 
    n = A.shape[0]                                 | 
                                                   | 
    results = np.empty((sz**3, n))                 | 
    tmp = np.linspace(-scale, scale, sz)-----------| #41
                                                   | 
    for i1 in numba.prange(sz):--------------------| #42
        v = np.empty(n, dtype=np.float64)          | 
        v1 = tmp[i1]                               | 
        for i2, v2 in enumerate(tmp):              | 
            for i3, v3 in enumerate(tmp):          | 
                v[0] = v1    